### ISSUE TITLE
Router extras not working with Nuxt v2.5.1

### ISSUE THREAD

**Issue by nmfzone** [nuxt-community/router-extras-module#12]
Recently I was update Nuxt from 2.4.5 to 2.5.1, but it failed, since I use this package.

Here the full of stack trace..

```
ReferenceError: meta is not defined
  at ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:174:28)
  at promise.then (node_modules/@nuxt/utils/dist/utils.js:1724:43)
  at process._tickCallback (internal/process/next_tick.js:68:7)
  at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
  at startup (internal/bootstrap/node.js:285:19)
  at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
```

Wants to update nuxt router extras to `beta.0`, but it's not available yet on npm. Any solution?

**Comment by pi0** [comment]
Hi. Sorry for lack of info. The module has been renamed to `@nuxtjs/router-extras` so pleas simply rename.

The problem with the old version is that it combines CJS with ES syntax but it is resolved with 0.1.0-beta.0 and newer versions.
