### ISSUE TITLE
SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by cannap** [nuxt-community/router-extras-module#75]
i delete .nuxt node_modules package-lock same error i have no idea i also added it to transpile
```
ATAL  SyntaxError: Unexpected identifier                            16:51:25

  at parse (node_modules/gray-matter/lib/engines.js:48:13)
  at Object.parse (node_modules/gray-matter/lib/engines.js:46:16)
  at module.exports (node_modules/gray-matter/lib/parse.js:12:17)
  at parseMatter (node_modules/gray-matter/index.js:109:17)
  at matter (node_modules/gray-matter/index.js:50:10)
  at extractExtrasFromRoute (node_modules/@nuxtjs/router-extras/lib/extras.js:88:20)
  at async extendRoutes (node_modules/@nuxtjs/router-extras/lib/extras.js:19:20)
  at async Nuxt.callHook (node_modules/hable/lib/hookable.js:50:7)
  at async Builder.resolveRoutes (node_modules/@nuxt/builder/dist/builder.js:5801:5)
  at async Promise.all (index 1)
  at async Builder.generateRoutesAndFiles (node_modules/@nuxt/builder/dist/builder.js:5662:5)
  at async Builder.build (node_modules/@nuxt/builder/dist/builder.js:5585:5)
  at async Object._startDev (node_modules/@nuxt/cli/dist/cli-dev.js:84:5)
  at async Object.startDev (node_modules/@nuxt/cli/dist/cli-dev.js:48:20)
  at async Object.run (node_modules/@nuxt/cli/dist/cli-dev.js:43:5)
  at async NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-command.js:2567:7)


   ╭─────────────────────────────────────────────────────╮
   │                                                     │
   │   ✖ Nuxt Fatal Error                                │
   │                                                     │
   │   SyntaxError: SyntaxError: Unexpected identifier   │
   │                                                     │
```

node version 12.5.0
nuxt 2.9.2
Macos

thanks

**Comment by cannap** [comment]
it just works now i dont know what happens i updated nuxt

**Comment by cannap** [comment]
hmm i dont know what happens same error again

**Comment by ardasatata** [comment]
I just experience this issue Im on nuxt 2.10.2 and then i updated using npm update to nuxt 2.11 still same, and i tried to downgrade to nuxt 2.10.2 again and its still happen same error

```
✔ Builder initialized                                                                                                             20:05:42

 FATAL  SyntaxError: Invalid or unexpected token                                                                                  20:05:42

  at parse (node_modules/gray-matter/lib/engines.js:48:13)
  at Object.parse (node_modules/gray-matter/lib/engines.js:46:16)
  at module.exports (node_modules/gray-matter/lib/parse.js:12:17)
  at parseMatter (node_modules/gray-matter/index.js:109:17)
  at matter (node_modules/gray-matter/index.js:50:10)
  at extractExtrasFromRoute (node_modules/@nuxtjs/router-extras/lib/extras.js:88:20)
  at async extendRoutes (node_modules/@nuxtjs/router-extras/lib/extras.js:19:20)
  at async Nuxt.callHook (node_modules/hable/lib/hookable.js:50:7)
  at async Builder.resolveRoutes (node_modules/@nuxt/builder/dist/builder.js:5829:5)
  at async Promise.all (index 1)
  at async Builder.generateRoutesAndFiles (node_modules/@nuxt/builder/dist/builder.js:5665:5)
  at async Builder.build (node_modules/@nuxt/builder/dist/builder.js:5590:5)
  at async Object._buildDev (node_modules/@nuxt/cli/dist/cli-dev.js:98:5)
  at async Object.startDev (node_modules/@nuxt/cli/dist/cli-dev.js:56:7)
  at async Object.run (node_modules/@nuxt/cli/dist/cli-dev.js:43:5)
  at async NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-command.js:2575:7)


   ╭───────────────────────────────────────────────────────────╮
   │                                                           │
   │   ✖ Nuxt Fatal Error                                      │
   │                                                           │
   │   SyntaxError: SyntaxError: Invalid or unexpected token   │
   │                                                           │
   ╰───────────────────────────────────────────────────────────╯

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pgs-frontend-pos@1.0.0 dev: `nuxt`
npm ERR! Exit status 1
npm ERR!
```

**Comment by javierriveros** [comment]
Thank you so much @Tinoooo, I had the same error but it wasn't too descriptive, after seeing your answer I checked my code and I was missing a comma in the routes.
